# ref: https://github.com/actions/runner-images
name: Build and Upload (amd64 Linux Python)

on:
  push:
    branches:
      - v13
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
env:
  CCACHE_BASEDIR: ${{github.workspace}}
  CCACHE_DIR: ${{github.workspace}}/.ccache

jobs:
  native:
    strategy:
      matrix:
        python: [
          {version: "3.13"},
         ]
      fail-fast: false
    name: amd64•Linux•CMake•Python${{matrix.python.version}}
    runs-on: ubuntu-latest
    env:
      deps_src_key: amd64_linux_python_deps_src_${{matrix.python.version}}
      deps_build_key: amd64_linux_python_deps_build_${{matrix.python.version}}
      ccache_key: amd64_linux_python_ccache_${{matrix.python.version}}
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build ccache swig
          swig -version
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python.version}}
      - name: Update Path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # RESTORING CACHES
      - name: Restore CMake dependency source code
        uses: actions/cache/restore@v5
        id: deps_src_restore
        with:
          key: ${{env.deps_src_key}}-${{hashFiles('CMakeLists.txt', 'cmake/**')}}
          path: ${{github.workspace}}/build/_deps/*-src
      - name: Restore CMake dependency build
        uses: actions/cache/restore@v5
        id: deps_build_restore
        with:
          key: ${{env.deps_build_key}}-${{hashFiles('CMakeLists.txt', 'cmake/**')}}
          path: |
            ${{github.workspace}}/build/_deps/*-build
            ${{github.workspace}}/build/_deps/*-subbuild
      - name: Restore CCache
        uses: actions/cache/restore@v5
        id: ccache_restore
        with:
          key: ${{env.ccache_key}}-${{github.sha}}
          restore-keys: ${{env.ccache_key}}-
          path: ${{env.CCACHE_DIR}}

      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "Ninja"
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
          -DBUILD_PYTHON=ON
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: >
          cmake --build build
          --config Release
          --target all
          -v -j2
      - name: Upload Python wheel
        uses: actions/upload-artifact@v7
        with:
          name: ortools-amd64-linux-python-${{matrix.python.version}}-wheel
          path: ${{github.workspace}}/build/**/*.whl
          if-no-files-found: error
          compression-level: 0
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config Release
          --target test
          -v
